### ISSUE TITLE
KeyError: '.' in cellSNP/pileup_utils.py causing failure of temp file merging

### ISSUE THREAD

**Issue by mpmargolis** [huangyh09/cellSNP#22]
Hello, I'm running into an error when calling cellSNP in mode 1 on mouse .bam data, specifically on chromosome 11, with the following command:

`~/.local/bin/cellSNP -s file.bam -b barcodes.tsv -O cellSNP_output_11 -R mgp.v5.snps_subset_11.vcf.gz -p 36 --minMAF 0.1 --minCOUNT 20`

This causes the following error after the pipeline has finished processing all positions:
```
100.00% positions processed.
multiprocessing.pool.RemoteTraceback:
"""
Traceback (most recent call last):
  File "/u/local/apps/anaconda3/2020.11/lib/python3.8/multiprocessing/pool.py", line 125, in worker
    result = (True, func(*args, **kwds))
  File "/u/home/m/margolis/.local/lib/python3.8/site-packages/cellSNP/utils/pileup_utils.py", line 294, in fetch_positions
    vcf_line = get_vcf_line(base_merge, base_cells, qual_cells,
  File "/u/home/m/margolis/.local/lib/python3.8/site-packages/cellSNP/utils/pileup_utils.py", line 366, in get_vcf_line
    ALT_cnt = base_merge[ALT]
KeyError: '.'
"""

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/u/home/m/margolis/.local/bin/cellSNP", line 8, in <module>
    sys.exit(main())
  File "/u/home/m/margolis/.local/lib/python3.8/site-packages/cellSNP/cellSNP.py", line 268, in main
    result = [res.get() for res in result]
  File "/u/home/m/margolis/.local/lib/python3.8/site-packages/cellSNP/cellSNP.py", line 268, in <listcomp>
    result = [res.get() for res in result]
  File "/u/local/apps/anaconda3/2020.11/lib/python3.8/multiprocessing/pool.py", line 771, in get
    raise self._value
KeyError: '.'

```

Here is the segment of code in the pileup_util.py file throwing an error:

![image](https://user-images.githubusercontent.com/93281145/139117715-a9549516-3a11-426c-8c5c-daf45270823a.png)

I'm assuming that this means an alternate allele wasn't found in one of the temp files, causing an issue with combining the temp files into the final output file. Any suggestions on how to prevent this in the future? I have found that changing minMAF and minCOUNT (making them more stringent) seems to get rid of the issue, but I would like to keep these values consistent across all my analyses. This issue seems to pop up randomly, though more often with smaller chromosomes. Mouse chromosomes 1-10, 12-XY ran without issue.

**Comment by hxj5** [comment]
Hi, thanks for your feedback. Please check if any ALT allele is `'.'` in the input VCF. For now, cellSNP only checks if the REF or ALT allele in the input VCF is of length 1 (single character), but did not check if this character is one of "A, C, G, T, N".

**Comment by mpmargolis** [comment]
Thank you for the quick response! You were correct, some entries in the reference VCF have blank alternate alleles. I'll remove those lines and that should probably resolve the problem.
